#cloud-config
packages:
  - httpd
  - mariadb-server
  - mariadb
  - php
  - php-mysql
runcmd:
  - systemctl start httpd.service
  - systemctl enable httpd.service
  - systemctl start mariadb
  - systemctl enable mariadb.service
  - /usr/bin/mysqladmin -u root password 'secret'
  - mysql -u root -psecret -e "create user 'root'@'%' identified by 'secret';" mysql
  - mysql -u root -psecret -e 'CREATE TABLE mytable (mycol varchar(255));' test
  - mysql -u root -psecret -e "INSERT INTO mytable (mycol) values ('linuxacademythebest') ;" test
